### ISSUE TITLE
Instructions for running the application

### ISSUE THREAD

**Issue by Kneuman0** [fusilero/balistica#23]
Could not find instructions for running the application after it has been compiled and configured in the INSTALL text file. Could not find any executables in the root directory except autogen.sh

**Comment by steveno** [comment]
At this point I don't have a .desktop file being generated so it won't show up by default under your menu in Gnome3 or Unity. I'll have to work on adding something. If you're ambitious, feel free to beat me to it with a pull request.

After you build it, the program can easily run from the build directory with 
`./balistica`

**Comment by Kneuman0** [comment]
Perhaps I didn't build it correctly because I'm not seeing that executable in the root directory or a directory called "build"

I was getting these errors from running the "configure" executable, maybe this halted the build:
./configure: line 3843: syntax error near unexpected token `disable-static'

./configure: line 3843: `LT_INIT(disable-static)'

I'm running Ubuntu

**Comment by steveno** [comment]
Here is a gist of my build output following the INSTALL.md instructions. Can you post something similar so I can see what is going on for you?

https://gist.github.com/steveno/96ffc4bc31e3491bb90e5486338b38fe

**Comment by Kneuman0** [comment]
Here is a link to my log file:
https://github.com/Kneuman0/FileDownLoad/blob/master/log.log

Here is a link to the compiler config.log file:
https://github.com/Kneuman0/FileDownLoad/blob/master/config.log

**Comment by steveno** [comment]
I'm not 100% certian of exactly what you're missing, but your toolchain is broken for sure. It looks like you might be missing libtool.

**Comment by steveno** [comment]
If you need further help with this issue, please feel free to re-open this issue.
