### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [fusilero/balistica#46]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by steveno** [comment]
@Jibec I'm not real sure how this works. Do I just comment here with my answers?

1) which branch is your development branch? master
2) have you merged latest translation from Zanata and locked the project? No. Not sure how. I did make the project read only though.
3) what is the license of translation? Assuming they're the same license as the code, it's MPL v2.
4) do you have any announcement/warning you would like to display to the translators? No
5) do you need us to activate any specific checks? Not that I am aware of.
6) do you need us to automatically detect new translation files? Again, I really have no idea.

I'm really sorry that I'm so lost here. Frankly, I didn't think anyone would actually translate my stuff.

**Comment by Jibec** [comment]
I did it for you ;)

**Comment by Jibec** [comment]
done: https://translate.fedoraproject.org/projects/balistica

please log one time to the platform and tell me your username so I can add you as admin

weblate will update po files each time you update pot
weblate will update LINGUAS file
weblate will squash commits per author as long as the pull request stays open

any support request has to be done on translation mailing list: https://lists.fedoraproject.org/archives/list/trans%40lists.fedoraproject.org/

**Comment by steveno** [comment]
@Jibec My username is steveno.
